name: face_recognition_auth
description: "A powerful Flutter package that provides secure, reliable face recognition authentication using TensorFlow Lite and Google ML Kit. Implement face-based authentication in your Flutter apps with real-time face detection and a clean, customizable UI."
version: 1.0.0
homepage: https://github.com/mohadmed-adel/face_recognition_auth
repository: https://github.com/mohadmed-adel/face_recognition_auth
issue_tracker: https://github.com/mohadmed-adel/face_recognition_auth/issues
documentation: https://github.com/mohadmed-adel/face_recognition_auth

# Keywords for better discoverability on pub.dev
keywords:
  - authentication
  - face-recognition
  - biometric
  - security
  - tensorflow
  - ml-kit
  - camera
  - flutter

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.2
  google_mlkit_face_detection: ^0.11.0
  google_mlkit_commons: ^0.8.1
  image: ^4.5.4
  tflite_flutter: ^0.11.0
  path_provider: ^2.0.9
  path: ^1.8.0
  sqflite: ^2.0.2
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter assets configuration
flutter:
  # TensorFlow Lite model for face recognition
  assets:
    - assets/mobilefacenet.tflite
